# Generated by Django 3.1.1 on 2020-10-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Customer',
        ),
    ]
