# Generated by Django 3.1.1 on 2020-11-01 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_auto_20201031_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 11, 55, 55, 758400, tzinfo=utc), verbose_name='date published'),
        ),
    ]
