# Generated by Django 3.1.1 on 2020-11-02 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_auto_20201101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 5, 29, 52, 801400, tzinfo=utc), verbose_name='date published'),
        ),
    ]
