# Generated by Django 3.1.1 on 2020-11-02 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20201102_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 6, 43, 44, 360000, tzinfo=utc), verbose_name='date published'),
        ),
    ]
